# Generated by Django 5.1.3 on 2024-11-09 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_options_rename_date_event_start_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='processing_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='processing_error',
            field=models.TextField(blank=True),
        ),
    ]
