# Generated by Django 5.1.3 on 2024-11-16 15:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_processing_complete_event_processing_error'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventsGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('use_llm', models.BooleanField(default=False)),
                ('processing_complete', models.BooleanField(default=False)),
                ('processing_error', models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='event',
            name='use_llm',
        ),
        migrations.AddField(
            model_name='event',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='events.eventsgroup'),
        ),
    ]
