# Generated by Django 5.1.3 on 2024-11-16 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_remove_event_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='description',
        ),
    ]
