# Generated by Django 5.1.3 on 2024-11-16 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_remove_event_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventsgroup',
            options={'ordering': ['created_at']},
        ),
    ]
