# Generated by Django 5.1.3 on 2024-11-17 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_alter_eventsgroup_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventnote',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='events.event'),
        ),
    ]
