# Generated by Django 5.1.3 on 2024-11-19 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('system', 'System')], default='system', max_length=10)),
                ('language', models.CharField(choices=[('en', 'English'), ('zh-CN', 'Simplified Chinese'), ('zh-TW', 'Traditional Chinese')], default='en', max_length=10)),
                ('model_settings', models.JSONField(default=dict, help_text='Store model preferences like selected model, base URL etc.')),
                ('ollama_settings', models.JSONField(default=dict, help_text='Store Ollama-specific settings')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Preferences',
                'verbose_name_plural': 'System Preferences',
            },
        ),
    ]
